version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./public:/var/www/public
      - ./nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - "80:80"
    container_name: simple_nginx_html
